apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: hedera-transaction-tool
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      default_user = tool-back-end
      default_pass = plainpass