# SPDX-License-Identifier: Apache-2.0
name: "000: [USER] Official Release"

on:
  workflow_dispatch:
    inputs:
      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  packages: write
  contents: read
  pull-requests: read
  issues: read

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    name: Publish Official Release of Hedera Transaction Tool
    # MacOS runner for future compatibility (when frontend builds get added to semantic release)
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Install GnuPG Tools
        run: brew install gnupg

      - name: Import GPG Key
        id: gpg
        uses: step-security/ghaction-import-gpg@69c854a83c7f79463f8bdf46772ab09826c560cd # v6.3.1
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          git_tag_gpgsign: false
          git_config_global: true
          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: latest

      - name: Setup Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: "v3.12.3"

      - name: Log in to the Container registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin

      - name: Install Semantic Release
        if: ${{ github.event_name == 'workflow_dispatch' && !cancelled() && !failure() }}
        run: |
          npm install -g semantic-release@24.2.0 @semantic-release/git@10.0.1 @semantic-release/github@11.0.1 \
            @semantic-release/exec@6.0.3 semantic-release-helm3@2.9.3 \
            conventional-changelog-conventionalcommits@8.0.0 \
            @commitlint/cli@19.5.0 @commitlint/config-conventional@19.5.0 \
            marked-mangle@1.1.10 marked-gfm-heading-id@4.1.1 semantic-release-conventional-commits@3.0.0

      # Both actual and dry-run semantic-release will output the new version
      # in the logs but actual release should also publish a tag&release on GitHub
      # The helm charts are published to the GitHub artifact registry
      # as part of the release process (configured in .releaserc)
      - name: Run Semantic Release
        if: ${{ !cancelled() && !failure() }}
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.gpg.outputs.name}}
          GIT_AUTHOR_EMAIL: ${{ steps.gpg.outputs.email}}
          GIT_COMMITTER_NAME: ${{ steps.gpg.outputs.name}}
          GIT_COMMITTER_EMAIL: ${{ steps.gpg.outputs.email}}
        run: |
          if [[ "${{ inputs.dry-run-enabled }}" == "true" ]]; then
            echo "Dry Running semantic-release now..."
            npx semantic-release --dry-run
          else
            echo "Running semantic-release now..."
            npx semantic-release --debug
          fi
